# BestDisplay配置文件

messages:
  # 插件消息前缀
  prefix: "&8[&bBestDisplay&8]&r "

settings:
  display:
    # 是否在实体头顶显示扣血横幅
    damage_above: true
    # 是否在实体头顶显示回血横幅
    healing_above: true
    # 是否在动作栏显示受击实体血量
    health_action_bar: true
    # 是否在掉落物上方显示名称与堆叠数信息
    drop: true
    # 是否在农作物上方显示成熟度
    crop: true
    # 是否在点燃的TNT上方显示爆炸倒计时
    tnt: true
    # 是否在村民头顶显示职业与等级信息
    villager: true
    # 是否在蜂巢/蜂箱上方显示蜜蜂数量与储蜜量
    bee_nest: true
    # 是否在熔炉/高炉/烟熏炉上方显示烧炼信息
    furnace: true
    # 是否在附魔台上方显示最大附魔等级
    enchanting_table: true
  sound:
    # 是否在玩家射中实体时播放音效
    arrow: true